### ISSUE TITLE
readFileEventStream.js running out of memory

### ISSUE THREAD

**Issue by damienleroux** [paigen11/file-read-challenge#1]
Hey @paigen11 

Thank you for sharing your code from your [itnext post](https://itnext.io/streams-for-the-win-a-performance-comparison-of-nodejs-methods-for-reading-large-datasets-pt-2-bcfa732fa40e)

I just tried it on my pc (window 10, node v8.12.0) but neither `readFileStream` or `readFileEventStream` were able to process the whole `itcont.txt` (3,49Go)

![image](https://user-images.githubusercontent.com/12717418/50611848-35cf1780-0ed8-11e9-90da-00592543de60.png)
![image](https://user-images.githubusercontent.com/12717418/50611856-3cf62580-0ed8-11e9-9d2e-f88ff8acf22a.png)

How did you execute your test? Have you any clues about why `event-stream` did worked for me?

**Comment by paigen11** [comment]
Hi @damienleroux ,

The `readFileStream` shouldn't be able to normally process that file size on its own because it tries to hold the entire file in memory, and Node's default memory size is only 1.67GB. I'm not entirely sure why `event-stream` didn't work for you. As I said, when I downloaded the file it was 2.55GB in size.

One thing I might suggest, which I added in the README.md is increasing Node's memory size in the command line using `node --max-old-space-size=8192 readFileEventStream.js`. 

I was unaware of this when I wrote the blog, but another reader suggested it in the comments afterwards. This essentially gives Node 8GB of memory, so as long as it doesn't hog all your computer's resources to the point of crashing it, it might work for you.

I hope this helps.

**Comment by damienleroux** [comment]
From what I experienced, `readFileStream` or `event-stream` work both very well when streaming, if only counting the number of lines.

As soon as more data (names, dates) needs to be stored in variables, the memory ends exceeding the max space size because too much is stored. But If I don't store anything except counting lines, the memory heap size stay stable.

In your scripts, I saved only the line count and added at the beginning of the scripts some code to get the heap size every 1 second:

Example for `readFileStream.js`:

```javascript
var fs = require('fs');
var readline = require('readline');
var stream = require('stream');
var util = require('util');

var instream = fs.createReadStream('itcont.txt');
var outstream = new stream();
var rl = readline.createInterface(instream, outstream);

//get line count for file
var lineCount = 0;

function getHeapSize() {
  const used = process.memoryUsage().heapUsed / 1024 / 1024;
  console.log(`line count: ${lineCount}. Heap: ${Math.round(used * 100) / 100} MB`);
  setTimeout(getHeapSize, 1000);
}
getHeapSize();

rl.on('line', function (line) {
  lineCount++;
});

rl.on('close', function () {
  // total line count
  console.log(lineCount);
});
```

Results for `readFileStream.js`:

![image](https://user-images.githubusercontent.com/12717418/50659320-89a33480-0f9c-11e9-9589-7025c7734719.png)

Example for `readFileEventStream.js`:

```javascript
var fs = require('fs');
var es = require('event-stream');
var util = require('util');

//get line count for file
var totalLines = 0;

function getHeapSize() {
  const used = process.memoryUsage().heapUsed / 1024 / 1024;
  console.log(`line count: ${totalLines}. Heap: ${Math.round(used * 100) / 100} MB`);
  setTimeout(getHeapSize, 1000);
}
getHeapSize();

var s = fs
  // .createReadStream('test.txt')
  .createReadStream('itcont.txt')
  // .createReadStream('/Users/pxn5096/Downloads/indiv18/itcont.txt')
  .pipe(es.split())
  .pipe(
    es
      .mapSync(function (line) {
        totalLines++;
      })
      .on('error', function (err) {
        console.log('Error while reading file.', err);
      })
      .on('end', function () {
        console.log('Read entire file.');
        console.log(totalLines);
      })
  );

```
Results for `readFileEventStream.js`:

![image](https://user-images.githubusercontent.com/12717418/50659446-f0285280-0f9c-11e9-9bb2-0eaa31a7f99a.png)

As you can see, the heap size remains stable in each cases (max 18MB).

Thank you for your tips about `--max-old-space-size` but I don't need it for now, I just read you post and didn't understand why `event-stream` could solve the large file loading issue instead of `stream`. Great if it solves your problem but I can't say why.

Last thing strange to me when reading you script: `console.time('line count');` should not be defined inside the function processing the line because it is reset the time on each line until the close event triggers `console.timeEnd('line count');` and return the time for one line only.

Thank you for your answer and posts 👍
